### ISSUE TITLE
[Bug] Ratings not respecting user choice

### ISSUE THREAD

**Issue by loeffelpan** [jurialmunkey/skin.arctic.zephyr.2#67] opened 2019-06-02 17:28 UTC
The setup of shown rating is not working properly.
Please take a look at my screeshot and the result in my settings.xml.
I think it is inverted of what is shown in the settings dialog.

https://ibb.co/v3Y94ys

```
osmc@osmc:~$ cat .kodi/userdata/addon_data/skin.arctic.zephyr.2/settings.xml | grep rating
    <setting id="ratings.imdb" type="bool">true</setting>
    <setting id="ratings.top250" type="bool">false</setting>
    <setting id="disablestarrating" type="bool">true</setting>
    <setting id="ratings.metacritic" type="bool">false</setting>
    <setting id="ratings.tvdb" type="bool">true</setting>
    <setting id="ratings.rottentomatoesaudience" type="bool">false</setting>
    <setting id="ratings.rottentomatoes" type="bool">false</setting>
    <setting id="ratings.user" type="bool">false</setting>
    <setting id="ratings.themoviedb" type="bool">true</setting>
    <setting id="ratings.oscars" type="bool">false</setting>
```

**Comment by loeffelpan** [comment] 2019-06-02 20:32
Beside to this issue, even when set properly my single widget horizontal homescreen does not show IMDB ratings for movies. Just TVShows show TVDB ratings. Spotlight widgets shows IMDB ratings.
And is there a checkbox missing for TMDB?

**Comment by jurialmunkey** [comment] 2019-06-02 22:05
With a clean install, kodi sets all skinsettings to "false". However, I don't want all ratings to be disabled by default - so for ratings which are enabled by default in the skin, the corresponding skin setting is set to "true" when they are disabled; whereas ratings that are disabled by default must be set to "true" to enable them in the skin.

It has to be done this way because kodi doesn't have a reliable way to ensure that skin settings are initialised to the desired values when resetting settings or deleting guisettings etc.

**Comment by jurialmunkey** [comment] 2019-06-02 22:16
If you don't have a TheMovieDb option, then you aren't using the most recent version of the skin. Please make sure you have the most recent version.

https://i.imgur.com/MhGw5Hy.png

**Comment by loeffelpan** [comment] 2019-06-03 17:01
OK. Then this inverted thing is by design an not a bug.
I'm up to date with the alpha repo but this is 0.9.33~alpha1. I just updated to alpha7.

TheMovieDB show up in settings dialog. Fine, but only this setting is disabled by default and has to be true, when ratings show up. Maybe you should name those setting `rating.disable_tvdb` to be cleat what that option does (as you did for `disablestarrating`).

IMDB rating are not showing in single widget with movies (smart playlist: unwatched movies).
IMDB ratings are visible e. g. in spotlight widget.

IMDB Top250 rank shows up any time. Setting seems to be ignored.

**Comment by loeffelpan** [comment] 2019-06-03 18:02
WTF? I just set up API key for OMDB and TMDB to get metacritic and rotten tomatos.
Now I got IMDB ratings in my widgets.
Is that like it should work?

**Comment by jurialmunkey** [comment] 2019-06-03 21:34
No top250 should respect setting - I'll have a proper look when I have some time on the weekend

**Comment by loeffelpan** [comment] 2019-06-04 03:56
Thank you.
And shouldn’t IMDB ratings are shown without api keys? Maybe you can take a look at this, too. Worked for me only in spotlight widget, as I said above.

**Comment by jurialmunkey** [comment] 2019-09-08 04:21
I'm not sure why I never replied here.

Top250 bug should be fixed (at least I can't reproduce anymore).

The IMDb issue should be fixed too. The skin should now always use the star rating for library ratings. IMDb logo is only ever used for online ratings from a Helper plugin. Before this was inconsistent where the default showcase view would use the IMDb logo for library ratings whereas everywhere else stars were used for library rating (the skin can't actually tell where the library rating comes from, so it has to have a generic icon).
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.49-alpha2

I can't change the names of the skinsetting variable names without forcing users to reconfigure their settings - which I don't want to do.

**Closed by jurialmunkey** 2019-09-08 04:21 UTC
