### ISSUE TITLE
Header keeps "autohiding"

### ISSUE THREAD

**Issue by rekkisomo** [jurialmunkey/skin.arctic.zephyr.2#101] opened 2019-08-20 01:14 UTC
Using `Horizontal menu | Multiple widgets` and the Menu style to Icons, the header seems to now for some reason autohide after a few seconds when sitting on any page of home, leaving only the icons displayed in the middle.

**Comment by jurialmunkey** [comment] 2019-08-20 22:31
I can't recreate this issue and I'm not sure what might be causing it.
If you figure out any other related details/settings etc. that might be contributing to it, let me know and I'll look into it.

**Comment by rekkisomo** [comment] 2019-08-21 13:49
That's very weird. Looks like the issue is coming from `Display plot overlay after delay` being enabled. Fixed when disabled.

**Comment by jurialmunkey** [comment] 2019-08-24 03:44
Okay, yep the plot overlay setting is definitely causing the issue. I'm pretty sure I know what the problem is. Once I have a fix, I'll let you know.

**Comment by jurialmunkey** [comment] 2019-08-24 04:12
Should be fixed now. 
See:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.44-alpha1

Let me know if this setting causes issues elsewhere and I will fix it.

**Closed** 2019-08-24 05:19 UTC
